### ISSUE TITLE
Unable to record video with front camera

### ISSUE THREAD

**Issue by mzeeshanid** [imaginary-cloud/CameraManager#100]
Steps to reproduce:

- Download and run the CameraManager example project.
- Turn on flash and change camera to front.
- Tap on record button, it is giving a flash on back camera (Like capturing a photo) and nothing else happen when tap on stop recording button.

**Comment by cathy810218** [comment]
Yea, it doesn't work for me. It keeps saying the cameraOutputMode is stillImage..............

**Comment by torrao** [comment]
@mzeeshanid @cathy810218 

fixed in v3.1.4, thanks for your contribution 👍
