### ISSUE TITLE
Front camera flips photo

### ISSUE THREAD

**Issue by gbmksquare** [imaginary-cloud/CameraManager#102]
Photos took by front camera is flipped after saving. 

Though this is the default iOS behavior, since there are lots of people who prefer their selfie not bing flipped, it'll be great if there is a property to flip the front camera photo when saving to photo library.

**Comment by FaridHaddad** [comment]
Same for me .. did you solve this ?

**Comment by gbmksquare** [comment]
@FaridHaddad Created a new pull request resolving this issue.

**Comment by said13** [comment]
Front camera flips video

**Comment by qhu91it** [comment]
I found movieOutput.connections always empty when movieOutput created, so func _setupVideoConnection call only when movieOutput is nil and setting mirror is not working, I change like this to work
```
fileprivate func _getMovieOutput() -> AVCaptureMovieFileOutput {
    if movieOutput == nil {
        _createMovieOutput()
    } else {
        _setupVideoConnection() // <--- add this
    }
    return movieOutput!
}
```
