### ISSUE TITLE
[Bug] The function _performShutterAnimation makes UI slower

### ISSUE THREAD

**Issue by letien91** [imaginary-cloud/CameraManager#103]
Step:
- Switch to camera front
- Switch to camera back
- Switch to camera front
- Switch to camera back
.....
then take a photo. It is delay many times.

**Comment by jf367** [comment]
Yes, and even when doing it for the first time, the animation seems to add significant delay to capture speed. For example, capturing an image from front camera alone takes about 50 milliseconds, but the shutter animation adds another 300-500 milliseconds to that. It will be nice to have an option to disable shutter animation completely.

**Comment by torrao** [comment]
@letien91 @jf367,

in v3.1.4 was added a property `animateShutter` which can be used to disable the shutter animation. You can also disable the flip animation, when changing between front and back camera, using the `animateCameraDeviceChange` property.
