### ISSUE TITLE
Getting same video URL, when simultaneously recording video.

### ISSUE THREAD

**Issue by AkhileshiTest** [imaginary-cloud/CameraManager#108]
I am implementing feature like what'sApp on camera screen, Tap for photo and hold to record video, if i simultaneously records videos than i get the same videoURL in response. In short an array having same videoURL at all indexes. 

self.cameraManager.stopVideoRecording({ (videoURL, error) -> Void in
            if let errorOccured = error {
                self.cameraManager.showErrorBlock("Error occurred", errorOccured.localizedDescription)
            }
            print("videoURL...\(videoURL)")
})

**Comment by torrao** [comment]
@AkhileshiTest,

should be fixed in the v3.1.4. I'm appending to the filename the milliseconds since 1970.
