### ISSUE TITLE
Smooth transition.

### ISSUE THREAD

**Issue by Marlunes** [imaginary-cloud/CameraManager#109]
Any advice on how to handle smooth transition between .stillImage and .videoWithMic cameraOutput? 

Please I need help.

**Comment by torrao** [comment]
@Marlunes what do mean? If you are referring to switching between Image and Video, when using the provided Example app, the transition feels smooth IMHO.

**Comment by gamafranco** [comment]
Closing this until further clarification. Please reopen if still applicable.
