### ISSUE TITLE
Still Image Rotation Issue

### ISSUE THREAD

**Issue by ahmedwasil** [imaginary-cloud/CameraManager#111]
On a iPhone 6 or 6 Plus, this issue does not exist but occurs on iPhone 7.

As I capture a picture while the device is in Horizontal orientation, The image is captured, stretched and rotated to Vertical orientation before being displayed in a imageView. 

This only occurs on iPhone 7, both devices are on same iOS. On iPhone 6, the image is captured Horizontal orientation and stays in horizontal orientation. 

Any Idea why this would be occurring?

**Comment by ahmedwasil** [comment]
cameraManager.showAccessPermissionPopupAutomatically = true
        cameraManager.shouldRespondToOrientationChanges = true
        cameraManager.writeFilesToPhoneLibrary = false
        cameraManager.shouldKeepViewAtOrientationChanges = true

**Comment by torrao** [comment]
@ahmedwasil there were bug fixes to the orientation of the images in previous versions. If this problem still persists, please feel free to open a new issue.
