### ISSUE TITLE
I found BUGS.

### ISSUE THREAD

**Issue by Marlunes** [imaginary-cloud/CameraManager#115]
1. Default output is .stillImage, Default Flash to .off
2. Set Flash to .on
3. Change the output to .videoWithMic
4. Change the device camera to .back
5. Record a video

Bugs: Recorded video doesn't have sound(sound works fine with front device)
           Flash/Torch Doesn't work.

**Comment by Marlunes** [comment]
Actually the bug is when you change the cameraDevice and record a video, the audio is mute.

**Comment by brettmwright** [comment]
Any updates on this? I am having the same problem.

**Comment by brettmwright** [comment]
@Marlunes

**Comment by Jacolack** [comment]
Still having this problem, does anyone know a fix or if this is going to be fixed?

**Comment by torrao** [comment]
@Marlunes,

the issue regarding video not having sound it's fixed on v4.0.2.
The Flash issue still needs more work.

**Comment by torrao** [comment]
Closing this issue, because it was a list of bugs that were resolved in previous versions.
