### ISSUE TITLE
Not able to to get sound while recording from front camera

### ISSUE THREAD

**Issue by IOSPUNIT** [imaginary-cloud/CameraManager#116]
Hi,
     while i am trying to record video using front camera and back camera , after that going to merge 
     both video then i am unable to get sound from video which i recorded from Front camera.
    In case of back camera its working fine.
Thanks

**Comment by brettmwright** [comment]
Any update on this? I am having the same problem.

**Comment by brettmwright** [comment]
@IOSPUNIT

**Comment by essej** [comment]
I found and fixed this with the attached patch. @IOSPUNIT @brettmwright
[CameraManagerFixAudio.txt](https://github.com/imaginary-cloud/CameraManager/files/1717425/CameraManagerFixAudio.txt)

**Comment by torrao** [comment]
@IOSPUNIT @brettmwright this should be working in v4.0.2.
