### ISSUE TITLE
Urgent: toggle camera back to front no sound coming in recorded video

### ISSUE THREAD

**Issue by IOSPUNIT** [imaginary-cloud/CameraManager#118]
I am recording video from back camera and see sound is coming in video and now toggle camera then recorded from front camera but in recorded video sound is not coming.

**Comment by brettmwright** [comment]
Any update on this? I am having the same problem.

**Comment by brettmwright** [comment]
@IOSPUNIT

**Comment by essej** [comment]
I found and fixed this with the attached patch. @IOSPUNIT @brettmwright 

[CameraManagerFixAudio.txt](https://github.com/imaginary-cloud/CameraManager/files/1717418/CameraManagerFixAudio.txt)
