### ISSUE TITLE
Toggle between camera delays in AVCaptureVideoDataOutputSampleBufferDelegate

### ISSUE THREAD

**Issue by ChanchalW** [imaginary-cloud/CameraManager#119]
Hi, I am using this class for the camera. I just added AVCaptureOutput to get sample buffer because I want to show the filtered image in a live camera like many other beauty camera apps and it's working as I want.  
**Issue:-** 
When I toggle between camera  **(front to back) or (back to front)** delegate suddenly calls after delay about 10-15 second. I don't know where is the issue. I tracked the whole camera changing process taking only 0.7 seconds. 

# **Any help???**

**Comment by torrao** [comment]
@ChanchalW 

sorry, but since we are not implementing `AVCaptureVideoDataOutputSampleBufferDelegate` we cannot give you support for that.
