### ISSUE TITLE
Converting to Swift 4 - issue with capture function (renamed by Xcode9)

### ISSUE THREAD

**Issue by MehdiChennoufi** [imaginary-cloud/CameraManager#120]
Hey everyone, 

I'm trying to convert my Swift 3 project to Swift 4 for iOS11 but I encounter one error that I'm not sure to understand, this part cause me an issue because URL is not an optional anymore, I got it but I don't know how to re-write this part without breaking anything.

Xcode renamed the "capture" function "fileOutput" I'm ok with that, it should't cause any trouble but I got this :

![unknown](https://user-images.githubusercontent.com/17626617/30391170-c5f314e8-98b8-11e7-9205-d26281f7bbc1.png)

I tried to rewrite this part like this but I'm really not sure.... Any help appreciate :)

![unknown-1](https://user-images.githubusercontent.com/17626617/30391242-f6db8432-98b8-11e7-8ab2-e7fdf2c904dc.png)

**Comment by multinerd** [comment]
Simply change the line 
    
    if let outputFileURL = outputFileURL, writeFilesToPhoneLibrary {

to 

    if writeFilesToPhoneLibrary {

**Comment by MehdiChennoufi** [comment]
Hello multinerd, that's exactly what I tried and it's works great !

Thank you for your answer
