### ISSUE TITLE
Issue with focus area

### ISSUE THREAD

**Issue by MutahirPirzada** [imaginary-cloud/CameraManager#137]
attaching two images... image one is a screenshot of camera view .... in it you can see at left bottom... keyboard button v can be seen... 

image 2 is screenshot of captured image.. here image includes some extra area that was not visible in capture section (refer: image 1)

like at bottom left image 1 : V is the key that can be seen at edge..
in image 2: C is also captured

i checked your sdk... installed your example project.. it also has same issue 
![image1](https://user-images.githubusercontent.com/26282446/34639340-199ff8c6-f300-11e7-8f5c-380ddfb230d6.PNG)
![Uploading image2.PNG…]()

**Comment by Usman4Github** [comment]
![image1](https://user-images.githubusercontent.com/5094671/34639527-5e59cc82-f303-11e7-9c5f-056a951dc063.PNG)
![image2](https://user-images.githubusercontent.com/5094671/34639528-5ebdc778-f303-11e7-9ca3-6f67e5503b91.PNG)

here are images mentioned in above issue

**Comment by torrao** [comment]
@MutahirPirzada @Usman4Github 

this issue is fixed in v4.0.2 and was related to the UIImageView used for the preview not being `. scaleAspectFill`
