### ISSUE TITLE
AVCaptureDevice.requestAccess only work when the permissions are not yet determined

### ISSUE THREAD

**Issue by zhouhao27** [imaginary-cloud/CameraManager#149]
If there is a way to always ask for permission if the access is not granted.

**Comment by torrao** [comment]
@zhouhao27 

unfortunately no.

As seem [here](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624584-requestaccess): 

> After the user grants recording permission, the system remembers the choice for future use in the same app, but the user can change this choice at any time using the Settings app.

So it's the App's responsability to inform the user to go to the Setting app to change the permission.
