### ISSUE TITLE
Setting Camera as initial device

### ISSUE THREAD

**Issue by AdventureOfMar** [imaginary-cloud/CameraManager#15]
Hello, for starters thank you tremendously for this launching point it's so hard to find any references or help in understand the camera functionality for ios 8. My question is really quick, I noticed that in the actual view controller for where the camera will be shown it's possible to set which device opens first.

In your code you have   self.cameraManager.cameraOutputMode = .StillImage and for instance if I were to write  self.cameraManager.cameraDevice = .Front the front camera would launch as soon as the camera session starts instead of the back. My question is this i have self.cameraManager.cameraOutputMode = .StillImage set but no matter what I try the video camera opens up initially anyways. Is their a way to override this in your cameraManager class?

**Comment by nelanelanela** [comment]
I'm not sure if I understood your question well. What are you expecting to see on screen when you set self.cameraManager.cameraOutputMode = .StillImage?

**Comment by AdventureOfMar** [comment]
Hello, Sorry for phrasing my question so strangely. By setting the self.cameraManager.cameraOutputMode = .StillImage I'm expecting the camera to be the initial device that's ready to use. Like by default the regular camera opens up and then clicking a switch to change to the video camera would start recording video. Instead what I'm getting is no matter; if I set the OutputMode to = .VideoWithMic or .VideoOnly the device always initially opens up with the  .VideoWithMic settings i.e. the device starts recording video when clicking the record button instead of just taking a picture.

**Comment by AdventureOfMar** [comment]
I figured it out, I was just changing the initial device in the wrong location
