### ISSUE TITLE
Logo for CameraManager

### ISSUE THREAD

**Issue by hafizahmmed** [imaginary-cloud/CameraManager#151]
Hello,
Good Day, i make a logo icon for your project. If you want to use this logo in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.It's totally free for open source project.

![cameramanager-01](https://user-images.githubusercontent.com/38810169/41529856-422301b8-7310-11e8-9d50-209055a8bb0e.jpg)

**Comment by torrao** [comment]
@hafizahmmed thanks for making a logo for CameraManager but we are using our company logo as an icon for branding purposes.
