### ISSUE TITLE
Flash on off not working.

### ISSUE THREAD

**Issue by pgorasva** [imaginary-cloud/CameraManager#152]

**Comment by torrao** [comment]
@pgorasva 

can you please provide more info and steps to reproduce? Namely:
- are you using the example app?
- which version of CameraManager are you using?
- which iPhone model and iOS version are you using?

Thanks

**Comment by pgorasva** [comment]
No i am not using example app.
i am using 4.1 camera manager version
iPhone model : iPhone SE 
iOS version: 11

**Comment by torrao** [comment]
@pgorasva 

can you please try the example app in that same phone to see if the flash works?

**Comment by pgorasva** [comment]
@torrao 

i tried example app.
but flash working only in photo capture.when i try to record video flash was not working.

**Comment by xC0der** [comment]
I'd bet it because it changed to **torch** for video in a prior iOS update.  I'll have a look at the code and see what I can find @torrao

**Comment by torrao** [comment]
@pgorasva @xC0der 

I've made a PR #153 for fixing this and releasing it the next hour or so.

Basically I'm setting `AVCaptureDevice.flashMode` when `CameraOutputMode.stillImage` and `AVCaptureDevice.torchMode` otherwise (`CameraOutputMode.videoWithMic` or `CameraOutputMode.videoOnly`)

**Comment by xC0der** [comment]
That should do it!  Super fast turn around, nice work.

**Comment by pgorasva** [comment]
@torrao 

yes. it's working but there is one issue. when stop video recording flash doesn't off.

**Comment by pgorasva** [comment]
it's working.

Thanks @torrao  @xC0der
