### ISSUE TITLE
logo for CameraManager

### ISSUE THREAD

**Issue by hafizahmmed** [imaginary-cloud/CameraManager#155]
Hello,
Good Day, i make a logo icon for your project. If you want to use this logo in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.It's totally free for open source project.

![cameramanager-01](https://user-images.githubusercontent.com/38810169/41927739-d9e490fe-7994-11e8-85e2-eb29fdcf70d8.jpg)

**Comment by torrao** [comment]
@hafizahmmed thanks again for making a logo for CameraManager but we are using our company logo as an icon for branding purposes as discussed in #151
