### ISSUE TITLE
When recording is finished `videoURL` is always nil

### ISSUE THREAD

**Issue by dimovskidamjan** [imaginary-cloud/CameraManager#158]
@torrao  I tried recording a video running your example app (and with my own implementation) on my iPhone X with iOS 11, and the `videoURL` parameter in the completion block is always `nil`, but the `error` parameter is also `nil`. Is there something I'm missing?

**Comment by torrao** [comment]
@dimohamdy,

there was a bug which prevented the videoURL to be filled 👎 
I will release v4.2.2 in a few moments.

Thanks for the heads up 👍
