### ISSUE TITLE
Preview Layer is always on top

### ISSUE THREAD

**Issue by cohix** [imaginary-cloud/CameraManager#17]
I would like to be able to have views on top of the preview layer, i.e. have buttons added to the container view AFTER CameraManager.sharedInstance.addPreviewLayerToView(self.view) is called and have those views appear on top of the preview layer.

**Comment by nelanelanela** [comment]
The easiest way to achieve that is add a container view for the preview layer and add the buttons to the parent view. Check out the example project and let me know if you need any more help :-)
Thanks!

**Comment by cohix** [comment]
That is the solution I ended up using, but it would be nice if I could add the preview as a view instead of a layer :)
