### ISSUE TITLE
Swift 4.2 Support

### ISSUE THREAD

**Issue by rolandkakonyi** [imaginary-cloud/CameraManager#171]
The project should be converted using Xcode "Edit -> Convert -> to Current Swift Syntax..." feature.

I will submit a PR in a couple of minutes.

**Comment by Deg5112** [comment]
Any update on this? I have the same issue

**Comment by sacred0x01** [comment]
Any progress?

**Comment by rolandkakonyi** [comment]
Update has been submitted 27 days ago.

**Comment by gamafranco** [comment]
@rolandkakonyi Thanks for the PR. Sorry, we need to QA this and we're having trouble getting a bit of time to do it. Hang in there.
