### ISSUE TITLE
How to check videostabilization applied to video or not?

### ISSUE THREAD

**Issue by StellarKuldeep** [imaginary-cloud/CameraManager#177]
I want to stabilise the video while recording and for that I have used `videoStabilisationMode` property like below.

`cameraManager.videoStabilisationMode = .cinematic`

To test stabilisation I record video with shaking phone and i see recorded video but it looks like normal so please let me know how do I know `videoStabilisation` applied to that or not?

Thanks in advance.

**Comment by torrao** [comment]
@StellarKuldeep 

just released v5.1.3 which includes a property to check the currently active video stabilisation:  `cameraManager.activeVideoStabilisationMode`.

This is the stabilisation that will be used when recording a video. If video stabilisation is neither supported or active it will return `.off`.
