### ISSUE TITLE
star recording back camera that time record with black screen.

### ISSUE THREAD

**Issue by Mitesh-Mewada** [imaginary-cloud/CameraManager#179]
When i start video recording back camera start some millisecond recording black color. the contain of cameraView background color is clear. How to solve that ?

**Comment by Mitesh-Mewada** [comment]
Hey @AbyssAlora  i change my code as  #182 in CameraManager() class  but doesn't work if you implemented? so please share code with me.  How to solve that ?

**Comment by AbyssAlora** [comment]
Hey, try this and let me know if it's working. It's working well for me. 

    open func startRecordingVideo() {
        if cameraOutputMode != .stillImage {
            let videoOutput = _getMovieOutput()
            // setup video mirroring
            for connection in videoOutput.connections {
                for port in connection.inputPorts {
                    
                    if port.mediaType == AVMediaType.video {
                        let videoConnection = connection as AVCaptureConnection
                        if videoConnection.isVideoMirroringSupported {
                            videoConnection.isVideoMirrored = (cameraDevice == CameraDevice.front && shouldFlipFrontCameraImage)
                        }
                    }
                }
            }
            
    //            let specs = [kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier as String: AVMetadataIdentifier.quickTimeMetadataLocationISO6709,
    //                         kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType as String: kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709 as String] as [String : Any]
    //            
    //            var locationMetadataDesc: CMFormatDescription?
    //            CMMetadataFormatDescriptionCreateWithMetadataSpecifications(kCFAllocatorDefault, kCMMetadataFormatType_Boxed, [specs] as CFArray, &locationMetadataDesc)
    //            
    //            // Create the metadata input and add it to the session.
    //            guard let captureSession = captureSession, let locationMetadata = locationMetadataDesc else {
    //                return
    //            }
    //            
    //            let newLocationMetadataInput = AVCaptureMetadataInput(formatDescription: locationMetadata, clock: CMClockGetHostTimeClock())
    //            captureSession.addInputWithNoConnections(newLocationMetadataInput)
    //            
    //            // Connect the location metadata input to the movie file output.
    //            let inputPort = newLocationMetadataInput.ports[0]
    //            captureSession.add(AVCaptureConnection(inputPorts: [inputPort], output: videoOutput))
            
            _updateIlluminationMode(flashMode)
            
            videoOutput.startRecording(to: _tempFilePath(), recordingDelegate: self)
        } else {
            _show(NSLocalizedString("Capture session output still image", comment:""), message: NSLocalizedString("I can only take pictures", comment:""))
        }
    }

**Comment by Mitesh-Mewada** [comment]
Hey @AbyssAlora thanks for sharing  this code and it's absolutely working, Thanks. 👍👌‎😃
