### ISSUE TITLE
Is there a plan for adapter swift 5?

### ISSUE THREAD

**Issue by ceu** [imaginary-cloud/CameraManager#189]

**Comment by woutergoossens** [comment]
+1

**Comment by torrao** [comment]
@woutergoossens @ceu 

we are planning on releasing a new version this week which includes an update to Swift 5.0.

**Comment by torrao** [comment]
@woutergoossens @ceu 

just released [v.5.0.0](https://github.com/imaginary-cloud/CameraManager/tree/5.0.0)
