### ISSUE TITLE
Dark PreviewLayerView

### ISSUE THREAD

**Issue by rsassociates** [imaginary-cloud/CameraManager#19]
When I switching from .StillImage to .VideoWithMic and vice versa the PreviewLayerView becomes dark for a few seconds

**Comment by nelanelanela** [comment]
Can you give me some more details please, because I can not replicate that error. What device and iOS version were you running on?

**Comment by patthehuman** [comment]
i have the same issue. im on iphone 6s 9.1

**Comment by patthehuman** [comment]
@rsassociates any fix?

**Comment by AkhileshiTest** [comment]
When i click photo the very first time from all device with any iOS version.First clicked image always have a black shadow, and than all images continuous to be clicked normally.

**Comment by FaridHaddad** [comment]
@AkhileshiTest I have the same issue, did you solve it ?

**Comment by deepukjayan** [comment]
@torrao @AkhileshiTest @patthehuman Any update on this guys? I ended up having exact same issue.

**Comment by AkhileshiTest** [comment]
When you are adding layer to view to show camera feature, like in sample example the method addCameraToView have the function addPreviewLayerToView with parameter UIView, outputmode. i.e. Set the output mode to .stillImage instead of .videoWithMic

Regards
Akhilesh Sharma
Mo. +99812-81251

**Comment by deepukjayan** [comment]
That fixed the problem. Thanks.

**Comment by tapannathvani** [comment]
Even using .stillImage, getting first picture in dark mode. Can anyone please help me to solve this
