### ISSUE TITLE
IOS 12.2 background thread error On iPhone XS and XS Max

### ISSUE THREAD

**Issue by MoveElectricMobility** [imaginary-cloud/CameraManager#190]
when running version 4.4 on the newest iphones the following error is thrown: Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 13213, TID: 3634973, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0

it is working correctly on older phones like the iphone 6

**Comment by bernikowich** [comment]
Reproduced on iPhone XR (iOS 12.2).

**Comment by Splash04** [comment]
https://openradar.appspot.com/46210367

**Comment by HangyuYe** [comment]
This bug are not show on iOS 13 and other iPhones except Xs Xs-Max Xr on iOS 12.4, I think this should be iOS bug.

**Comment by torrao** [comment]
As reported by @Splash04 this an iOS bug that currently don't happen in most recent iOS versions.
