### ISSUE TITLE
NSLocationWhenInUseUsageDescription key must always be added to Info.plist

### ISSUE THREAD

**Issue by Johnson145** [imaginary-cloud/CameraManager#192]
Apple now requires that any app which uses this library need to specify the `NSLocationWhenInUseUsageDescription` key in the Info.plist file. This is the case eventhough one may have disabled all actual accesses to location data. Maybe this is worth a short notice in the Readme of this repo?

If you don't add the mentioned key, you can still successfully build and (try to) upload the app to App Store Connect. However, when doing the latter, you'll receive the following email by Apple:

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "App Name". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. **The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key** with a user-facing purpose string explaining clearly and completely why your app needs the data. **Starting Spring 2019**, all apps submitted to the App Store that access user data will be **required** to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. **While your app might not use these APIs, a purpose string is still required.** You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
> 
> Best regards,
> 
> The App Store Team

**Comment by gamafranco** [comment]
Thanks John. May I ask for a pull request?

**Comment by torrao** [comment]
Added to [README.md](https://github.com/imaginary-cloud/CameraManager/blob/master/README.md) on v5.1.0
