### ISSUE TITLE
mute/unmute audio during making video.

### ISSUE THREAD

**Issue by Sudhir9026** [imaginary-cloud/CameraManager#196]

**Comment by Sudhir9026** [comment]
Hi team,
My requirement is mute/unmute audio while video recording via the mute button. When the user tapped the mute button during making the video, audio should mute from video and also if I click unmute audio should come.

**Comment by torrao** [comment]
@Sudhir9026 

currently there's no public API that allows us to do that and if you try to do that with the default iOS camera, that's not possible either.
