### ISSUE TITLE
Help about Pausing the recording session.

### ISSUE THREAD

**Issue by EmadBeyrami** [imaginary-cloud/CameraManager#200]
is there any way to pause a video Capturing session? if it is I appreciate if you help. thank you

**Comment by torrao** [comment]
@EmadBeyrami,

sorry the late reply but there's no public API in `AVCaptureSession` that allows pausing a video capturing session.

**Comment by EmadBeyrami** [comment]
its ok pall I've finnished that project long ago. anyway, thanks.
