### ISSUE TITLE
Keep background music playing when switching to .videoWithMic

### ISSUE THREAD

**Issue by pennywise94** [imaginary-cloud/CameraManager#201]
I am using this library and so far it works great. Thank you for providing such a valuable library.

Currently, I am facing one issue. I have a button "Photo" and a button "Video" which switches between the cameraOutputMode, setting it to .stillImage and .videoWithMic respectively. However, as soon as I go into the video mode (.videoWithMic), any music playing in the background, either from Apple Music, Spotify, ... stops playing. Is there any way I can avoid this? I have tried setting up the AVAudioSession like so in either didFinishLaunchingWithOptions and in the function that sets the cameraOutputMode to .videoWithMic:

>     do {
>             try AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.ambient)
>             try AVAudioSession.sharedInstance().setActive(true)
>         } catch let error {
>             print(error.localizedDescription)
>         }

But this does not work. I also tried .playback, .playAndRecord and .record in the AVAudioSession. Also tried .mixWithOthers. Any suggestions?

**Comment by torrao** [comment]
@pennywise94,
 
when you use the system camera that's also what happens, and since we are using AVFoundation for controlling the camera, the CameraManager will mimic the system camera behaviour.

**Comment by aiyub007** [comment]
Somebody needs to find the solutions coz there are some apps that can do it
