### ISSUE TITLE
Pause/Resume recording

### ISSUE THREAD

**Issue by Asha-Pris** [imaginary-cloud/CameraManager#203]
Can you help with the pause/resume recording ?

**Comment by kpstar** [comment]
Hello, I am also curious how to pause/resume recording?

There is only start/stop recording function. Thanks.

**Comment by torrao** [comment]
@Asha-Pris @kpstar 

there's no public API in AVCaptureSession that allows pausing a video capturing session. Therefore the only way of doing that is recording a new video every time the user pauses and in the end merge all the videos into a single one.
