### ISSUE TITLE
Black photo first time

### ISSUE THREAD

**Issue by tapannathvani** [imaginary-cloud/CameraManager#206]
Hello,

I am getting first picture in Black overlay (taking pictures only, No video recording). I didn't changed any thing in framework. Please help me to solve it as I need to solve it ASAP.

**Comment by Sudhir9026** [comment]
Yes, I am also facing this issue. Any Idea how this fix?

**Comment by tapannathvani** [comment]
I commented this line
 //  cameraManager.resumeCaptureSession()
from viewWillAppear and its working fine for me. I don't know is it proper fixed or not but still I didn't get any issue related it. I am capturing image only not video.
