### ISSUE TITLE
hi, how to turn the shutter sound off?

### ISSUE THREAD

**Issue by Nomia** [imaginary-cloud/CameraManager#208]
Thank u for this great repo.

currently, I want to disabled the sound when I take a photo, but I don't see there is any config that can turn the sound off.

**Comment by Nomia** [comment]
It seems the sound configuration follow the system camera.

**Comment by Nomia** [comment]
But I still wanna know if there is a way to disable the sound in `CameraManager`.
thx

**Comment by torrao** [comment]
@Nomia,

we are using AVFoundation for controlling the camera and it doesn't provide a public API for doing that.
