### ISSUE TITLE
When App Minimises and Resume the App will crash

### ISSUE THREAD

**Issue by KiranDhokale8118** [imaginary-cloud/CameraManager#209]
Pause/Resume recording is possible ? Please help

**Comment by torrao** [comment]
@KiranDhokale8118 

I've tried minimising the Example App while recording a video and it didn't crash. Can you please try with the latest version: v5.1.0?

> Pause/Resume recording is possible ? Please help

If you want to implement that in your application you have to do that manually, which may involve recording multiple videos (one for every-time the user starts/unpauses) and merging all of them into a single video at the end.
