### ISSUE TITLE
Swift Package Manager not supported

### ISSUE THREAD

**Issue by taeger** [imaginary-cloud/CameraManager#215]
The installation with the Swift Package Manager in Xcode 11.3.1 fails with the error "The package dependency graph can not be resolved; unable find any available tag for the following requirements: ..."

**Comment by torrao** [comment]
@taeger 

this issue should be fixed in [v.5.0.0](https://github.com/imaginary-cloud/CameraManager/tree/5.0.0).
Please let me know if you have further issues.
