### ISSUE TITLE
Size of preview layer doesn't match

### ISSUE THREAD

**Issue by bryanhpchiang** [imaginary-cloud/CameraManager#216]
I'm adding a preview layer, but the size of the captured image does not match the size of the preview layer view. Any suggestions?

**Comment by bryanhpchiang** [comment]
Fixed

**Comment by lo5co** [comment]
I've this issue too. Captured image doesnt match preview layer. It seems that preview layer is zoomed in stillImage mode

**Comment by quangpc-ht** [comment]
I have this issue too. preview layer is square, but output image is not.
@zoink could u please tell me how to fix this issue.
