### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by leolelego** [imaginary-cloud/CameraManager#218]
No, update from a year now, no PR accepted. 
If is the case, just tell us, we will make an official fork 😊

**Comment by torrao** [comment]
@leolelego 

sorry but due to other projects we were unable to give attention to CameraManager. 

Right now I'm devoting some time to this project and expect to have a new version until the end of the week.

**Comment by torrao** [comment]
@leolelego 

just pushed [v.5.0.0](https://github.com/imaginary-cloud/CameraManager/tree/5.0.0).

**Comment by leolelego** [comment]
Awesome !
