### ISSUE TITLE
App crashes in iPhone 7 Plus

### ISSUE THREAD

**Issue by azimTalukdar-SI** [imaginary-cloud/CameraManager#219]
I am getting following crash report when I try to run it on my Device.

> "dyld: Library not loaded: @rpath/CameraManager.framework/CameraManager
  Referenced from: /private/var/containers/Bundle/Application/6967DDCA-86AB-440E-8E1F-81F5433EF659/SwiftyCamDemo.app/SwiftyCamDemo
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/6967DDCA-86AB-440E-8E1F-81F5433EF659/SwiftyCamDemo.app/Frameworks/CameraManager.framework/CameraManager: code signature invalid for '/private/var/containers/Bundle/Application/6967DDCA-86AB-440E-8E1F-81F5433EF659/SwiftyCamDemo.app/Frameworks/CameraManager.framework/CameraManager'

	/private/var/containers/Bundle/Application/6967DDCA-86AB-440E-8E1F-81F5433EF659/SwiftyCamDemo.app/Frameworks/CameraManager.framework/CameraManager: code signature invalid for '/private/var/containers/Bundle/Application/6967DDCA-86AB-440E-8E1F-81F5433EF659/SwiftyCamDemo.app/Frameworks/CameraManager.framework/CameraManager'

	/private/var/containers/Bundle/Application/6967DDCA-86AB-440E-8E1F-81F5433EF659/SwiftyCamDemo.app/Frameworks/CameraManager.framework/CameraManager: stat() failed with errno=1
	/private/var/containers/Bundle/Application/6967DDCA-86AB-440E-8E1F-81F5433EF659/SwiftyCamDemo.app/Frameworks/CameraManager.framework/CameraManager: code signature invalid for '/private/var/containers/Bundle/Application/6967DDCA-86AB-440E-8E1F-81F5433EF659/SwiftyCamDemo.app/Frameworks/CameraManager.framework/CameraManager'

	/private/var/containers/Bundle/Application/6967DDCA-86AB-440E-8E1F-81F5433EF659/SwiftyCamDemo.app/Frameworks/CameraManager.framework/CameraManager: stat() failed with errno=1
Message from debugger: Terminated due to signal 6"

**Comment by torrao** [comment]
@azimTalukdar-SI 

that seems to be a code signing error in your app and it's not related with CameraManager.
