### ISSUE TITLE
How to set maximum duration for a video?

### ISSUE THREAD

**Issue by zeona-n** [imaginary-cloud/CameraManager#229]
Is there any way to set maximum and minimum duration of video?

**Comment by kselvin** [comment]
I'm unsure if that is part of this library. But you can definitely use a timer once the user starts recording that determines whether the user can stop the recording, whether the video should stop recording on it's own, etc. 

https://www.hackingwithswift.com/articles/117/the-ultimate-guide-to-timer

**Comment by zeona-n** [comment]
@kselvin Thank u so much, I used timer to acheive the same and it's working.
