### ISSUE TITLE
missing focus and exposure mode, zoom also

### ISSUE THREAD

**Issue by flyhigh1402** [imaginary-cloud/CameraManager#27]
can any guys add 3 this mode i think all camera app need them

**Comment by jesusruizlopez** [comment]
+1

**Comment by nelanelanela** [comment]
Will work on this next. Thanks for suggesting it!

**Comment by flyhigh1402** [comment]
can you make it soon i really need it for final project app. I tried to create ur self but it not work :(

**Comment by zxw5775** [comment]
+1

**Comment by patthehuman** [comment]
I'm also looking for this feature! Is anyone working on this @nelanelanela? I can create these features and create a branch + PR once I finish it...

Thanks!

**Comment by vkhattar** [comment]
Any updates on having focus functionality ?

**Comment by vkhattar** [comment]
Here is an extension that you can use for onTouch focus and exposure. Call this method from a view controller and pass in the current coordintaes on the screen. 

` public extension CameraManager {
       public func focus(atPoint: CGPoint) {
          let captureDevice = AVCaptureDevice.devices().first as? AVCaptureDevice
          if let currentDevice = captureDevice {
            if currentDevice.isFocusModeSupported(AVCaptureFocusMode.AutoFocus) && currentDevice.focusPointOfInterestSupported {
                let focusPoint = self.previewLayer!.captureDevicePointOfInterestForPoint(atPoint)
                do {
                    try currentDevice.lockForConfiguration()
                    currentDevice.focusPointOfInterest = CGPoint(x: focusPoint.x, y: focusPoint.y)
                    currentDevice.focusMode = AVCaptureFocusMode.AutoFocus
                    if currentDevice.isExposureModeSupported(AVCaptureExposureMode.AutoExpose) {
                        currentDevice.exposureMode = AVCaptureExposureMode.AutoExpose
                    }
                    currentDevice.unlockForConfiguration()
                }
                catch {
                    fatalError("[CameraEngine] error lock configuration device")
                }
            }
        }
    }
`

**Comment by Poeticode** [comment]
There's a PR from zaubara that works beautifully. Even has a yellow square animate in and fade out around the area pressed.

**Comment by dkrusenstrahle** [comment]
Please merge zaubara´s PR.
