### ISSUE TITLE
Crash when trying to record video

### ISSUE THREAD

**Issue by mrbaker4** [imaginary-cloud/CameraManager#3]
When I call CameraManager.sharedInstance.startRecordingVideo(), my app crashes with the following error: 
-[AVCaptureMovieFileOutput startRecordingToOutputFileURL:recordingDelegate:] - no active/enabled connections.'

**Comment by nelanelanela** [comment]
Thanks for submitting an issue. I tired to solve it but couldn't replicate the bug. I made some changes to make sure the connection is alway there active, but can't mark the issue as solved cause I wasn't able to produce the crash even before the adjustments. Can you please provide some more details about the workflow to reproduce the error?

**Comment by mrbaker4** [comment]
I believe I was able to track down what happened. It seemed that the app I was building did not successfully prompt me for camera access and there was no way to force it in the settings view or for it to prompt. I think you can safely close this issue and I can reopen if I run into the issue again.

**Comment by aukaost** [comment]
I had a similar issue and it turned out that I called CameraManager.sharedInstance.resumeCaptureSession() before CameraManager.sharedInstance.addPreviewLayerToView(...) which lead to this error when trying to take a picture.

**Comment by nelanelanela** [comment]
Thanks again for submitting the issue, I was able to reproduce it and you're right it was about the camera permissions. It's fixed now and you can check in what state the camera device is.

**Comment by Shahbaz-Akram** [comment]
I also have same issue [AVCaptureMovieFileOutput startRecordingToOutputFileURL:recordingDelegate:] No active/enabled connections' please confirm me how i resolve it.

**Comment by Jacolack** [comment]
I have the same issue. The issue can even be replicated on the CameraManager example provided in the download. Simply press record as soon as the app launches.

**Comment by Shahbaz-Akram** [comment]
One thing more App crash only  first time when app install  .
