### ISSUE TITLE
error when trying to record video

### ISSUE THREAD

**Issue by robertoswald** [imaginary-cloud/CameraManager#30]
Hi,

I am trying to setup video recording. I have the following code:

        let cameraManager = CameraManager()
        
        cameraManager.cameraDevice = .Back
        cameraManager.cameraOutputMode = .VideoWithMic
        cameraManager.cameraOutputQuality = .High
        cameraManager.writeFilesToPhoneLibrary = true
        
        cameraManager.addPreviewLayerToView(self.imageView)

        
        cameraManager.startRecordingVideo()

I get the following error when startRecordingVideo is called: 

2015-12-23 22:52:25.643 RocketBash[1503:819683] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureMovieFileOutput startRecordingToOutputFileURL:recordingDelegate:] - no active/enabled connections.'

Anything else I need to do? or something I have done in error?

**Comment by nelanelanela** [comment]
Hi Roberto,

thanks a lot for reaching out. The problem is that setting up the camera works asynchronously and that's why you're getting the error. I added two things to solve that:

CameraIsReady property to determine if it's already good to use and a competition block on add to preview function.

Let me know if you have any more troubles.

Natalia

**Comment by robertoswald** [comment]
Hi,

Thanks for the quick response.

I am not getting that error anymore however when I now start the recording in the callback the camera seems to freeze. Do you have a sample project with the camera that I can use as a reference?

I am now making use of the following code:

let cameraManager = CameraManager()
        
        cameraManager.cameraDevice = .Front
        cameraManager.cameraOutputMode = .VideoWithMic
        cameraManager.cameraOutputQuality = .High
        cameraManager.writeFilesToPhoneLibrary = true

        cameraManager.addPreviewLayerToView(self.imageView, newCameraOutputMode: .VideoWithMic, completition: {
            print("Camera ready")

            cameraManager.startRecordingVideo()
        })

**Comment by nelanelanela** [comment]
Hi, you need to retain the cameraManager instance somewhere in order to retain all the configurations. 
I tested your code and if I put it directly as is it freezes, but if I save the cameraManager as an instance constant if works fine.

**Comment by robertoswald** [comment]
Will give that a try shortly.

**Comment by nelanelanela** [comment]
Ok, thanks for reporting. Do let us know if you need any more help! :-)
