### ISSUE TITLE
Just making some changes.

### ISSUE THREAD

**Issue by iamtomcat** [imaginary-cloud/CameraManager#31]
Hey not really an issue, but wanted to let you know I've been slowly working on a fork that you may want to eventually pull back into your project. It's not done on my end, but I keep pulling in your changes as they happen so it's pretty up to date with what you've done. 

I've already got zoom working on my end. Also I've gotten rid of the Assets library and switched to the photos framework.

**Comment by nelanelanela** [comment]
Ok, thanks for letting us know. Do you want to make a pull request or should I just take a look at the code and grab only what is generic enough?

**Comment by iamtomcat** [comment]
I'll do a pull request once I'm a little closer to be being finished. Then I can make any changes you want to see.

**Comment by nelanelanela** [comment]
Ok, thanks a lot for your help and for the heads up!
