### ISSUE TITLE
Recorded video has no sound

### ISSUE THREAD

**Issue by Wraecca** [imaginary-cloud/CameraManager#32]
It only happens when the video is longer than around 10 seconds. Easy to reproduce in sample project. That asset's tracksWithMediaType(AVMediaTypeAudio) is empty 😢

**Comment by nelanelanela** [comment]
Ok, thanks a lot for reporting, I'll take a look.

**Comment by alexkoltun** [comment]
Can be solved by adding:
movieOutput!.movieFragmentInterval = kCMTimeInvalid

just after AVCaptureMovieFileOutput creation in _setupOutputs func

On the side note, it is just unbelievable this setting is not kCMTimeInvalid by default, luckely I have found this post: http://stackoverflow.com/questions/26735627/ios-8-ipad-avcapturemoviefileoutput-drops-loses-never-gets-audio-track-after

**Comment by nelanelanela** [comment]
Wow, thanks so much for the hint, I'll test it out and release a new version with the fix!

**Comment by nelanelanela** [comment]
Thanks @alexkoltun for help and @Wraecca for reporting. I fixed that and pushed a new version.
