### ISSUE TITLE
capturePictureWithCompletition spells completion wrong

### ISSUE THREAD

**Issue by saturnial** [imaginary-cloud/CameraManager#33]
should be capturePictureWithCompletion

**Comment by iamtomcat** [comment]
I was going to fix this in my pull request. But then they'd have to bump the version to 3. I still have some massive changes that will hopefully be accepted that has all this fixed as well.

**Comment by torrao** [comment]
@saturnial, @iamtomcat Those mispellings are resolved in version 2.2.4.
