### ISSUE TITLE
Zoom 

### ISSUE THREAD

**Issue by AJBeltran3** [imaginary-cloud/CameraManager#34]
Need to update to add zoom. Mentioned before. This is a key aspect of a camera.

**Comment by iamtomcat** [comment]
I've added it to my fork if you want to grab it out of there.

**Comment by AJBeltran3** [comment]
Are you saying your camera will support zoom or already has zoom when you put this in the project?

**Comment by iamtomcat** [comment]
I don't know what "this" is, but I have code in my fork that you can copy and paste so you can support zoom if you need it right away.

**Comment by AJBeltran3** [comment]
This was meaning your fork. Sorry for the confusion. Was unable to locate the code that showed where zoom was supported. Will look again. Thanks!

**Comment by iamtomcat** [comment]
One sec I'll link to it if I can.

**Comment by iamtomcat** [comment]
https://github.com/iamtomcat/CameraManager/blob/refactor/CameraManager/CameraManager.swift#L436

**Comment by AJBeltran3** [comment]
Awesome thank you!

**Comment by gamafranco** [comment]
Hi @iamtomcat. thanks for the contribution.

Could you make a pull request please?

Thanks.

**Comment by iamtomcat** [comment]
Done.

**Comment by torrao** [comment]
Hi @AJBeltran3. The new version v2.2.0 supports zoom.

Thanks.
