### ISSUE TITLE
Switching between front and back camera whilst recording.

### ISSUE THREAD

**Issue by hassanmah** [imaginary-cloud/CameraManager#38]
Hi,

When I try to switch between front and back camera whilst recording, `cameraManager.stopRecordingVideo({ (videoURL, error) -> Void in })` is never called. 

Any ideas why?

Thanks

**Comment by torrao** [comment]
Hi @hassanmah,

are you using the example app included?

Thanks

**Comment by hassanmah** [comment]
Hi @torrao,

Yes I am, any idea why it's not being called?

Thanks

**Comment by junhohong** [comment]
I think it's because ` didFinishRecordingToOutputFileAt` delegate method is being called when you switch the camera. Do any of you know a way around this?

**Comment by torrao** [comment]
Closing this since there has not been any recent activity and newer versions have been released. 
Please open a new issue if the problem persists.
