### ISSUE TITLE
Unresolved identifier

### ISSUE THREAD

**Issue by sarbogast** [imaginary-cloud/CameraManager#4]
When I integrate CameraManager in my project via CocoaPods, it doesn't see the CameraManager class. The compiler says "Use of unresolved identifier 'CameraManager'. Is there anything special I should do to expose CameraManager class to my Swift classes? Obviously I don't have to add a #import to my bridging header, but I'm wondering if there's an equivalent. Note that I'm using CocoaPods 0.35 (the latest version to date).

**Comment by aukaost** [comment]
That's because the class isn't public. You can use it by copying it to your project or by patching up the class and related members to be public. I suppose the latter with a pull request is preferred. I might just do that.

**Comment by nelanelanela** [comment]
Fixed and pushed in the version 1.0.9. Thanks for creating the issue!
