### ISSUE TITLE
Image is rotated when I take the photo.

### ISSUE THREAD

**Issue by ChrisStayte** [imaginary-cloud/CameraManager#46]
I capture the photos and the image is rotated clockwise 90 degrees

**Comment by nthegedus** [comment]
@ChrisStayte I've got the same issue. Did you solve it?

**Comment by ChrisStayte** [comment]
@nthegedus 
I did solve it. I set it to UIImageJPEGRepresentation(img, 1.0); The PNG representation does not save "header" information that saves the rotation.
