### ISSUE TITLE
More than one output of the same type is unsupported.

### ISSUE THREAD

**Issue by RobinChao** [imaginary-cloud/CameraManager#49]
Sometimes, The Demo crashed and printed below log:

2016-04-22 17:42:48.136 camera[902:654638] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** Cannot add output <AVCaptureMovieFileOutput: 0x127e659a0> to capture session <AVCaptureSession: 0x127d44400 [AVCaptureSessionPresetPhoto]>
	<AVCaptureDeviceInput: 0x127e42fa0 [Back Camera]> -> <AVCaptureVideoPreviewLayer: 0x127e70d20>
	<AVCaptureDeviceInput: 0x127e42fa0 [Back Camera]> -> <AVCaptureMovieFileOutput: 0x127e72080>
	<AVCaptureDeviceInput: 0x127dd8340 [iPhone 麦克风]> -> <AVCaptureMovieFileOutput: 0x127e72080> because more than one output of the same type is unsupported.'
*** First throw call stack:
(0x18401ee38 0x183683f80 0x18a75cbd8 0x18a75c93c 0x1000f1b84 0x1000f23ec 0x1000f41c8 0x1000ed9d0 0x1000eda3c 0x1000fa2a4 0x1000fc72c 0x1000fa960 0x100795a7c 0x100795a3c 0x1007a2554 0x10079972c 0x100795a3c 0x1007a4c9c 0x1007a4364 0x183c81470 0x183c81020)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by torrao** [comment]
@RobinChao Thanks for the feedback. That issue is resolved in version 2.2.4.
