### ISSUE TITLE
Crash when trying to capture a still image

### ISSUE THREAD

**Issue by sarbogast** [imaginary-cloud/CameraManager#5]
When I run the following code:
```
CameraManager.sharedInstance.capturePictureWithCompletition({ (image) -> Void in
            self.imageView.hidden = false
            self.imageView.image = image
})
```

I get the following exception:

2014-12-02 21:27:39.343 Pixync[8928:3126855] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureStillImageOutput captureStillImageAsynchronouslyFromConnection:completionHandler:] - inactive/invalid connection passed.'
*** First throw call stack:
(0x187c7e59c 0x1983d00e4 0x186515140 0x100100360 0x1000ed4b8 0x1008b8e30 0x1008b8df0 0x1008c3854 0x1008bc120 0x1008c575c 0x1008c6f18 0x198bf12e4 0x198bf0fa8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by nelanelanela** [comment]
Thanks so much for submitting the issue and all the effort you put into solving the bug. I found the issue and fixed it, will release a new version any time soon.
Thanks again!
