### ISSUE TITLE
Square Photo and Video

### ISSUE THREAD

**Issue by xMonty** [imaginary-cloud/CameraManager#52]
Is it possible to take square shaped photo or video with this?

**Comment by klevison** [comment]
+1

**Comment by Fritiof** [comment]
Any updates regarding this? I have made the cameraview square but it doesn't seem to be what it deems as the actual image.. unfortunately

**Comment by patthehuman** [comment]
@Fritiof u ever figure this out

**Comment by Fritiof** [comment]
@patthehuman I ended up cropping it on my own actually.

**Comment by AlexSmet** [comment]
@Fritiof Thanks a lot!
I have implemented your code as extension for UIImage with Swift 3 
`extension UIImage {
    
    public func cropToBounds(width: CGFloat, height: CGFloat) -> UIImage {
        
        let contextImage: UIImage = UIImage(cgImage: self.cgImage!)
        
        let contextSize: CGSize = contextImage.size
        
        var posX: CGFloat = 0.0
        var posY: CGFloat = 0.0
        var cgwidth: CGFloat = CGFloat(width)
        var cgheight: CGFloat = CGFloat(height)
        
        // See what size is longer and create the center off of that
        if contextSize.width > contextSize.height {
            posX = ((contextSize.width - contextSize.height) / 2)
            posY = 0
            cgwidth = contextSize.height
            cgheight = contextSize.height
        } else {
            posX = 0
            posY = ((contextSize.height - contextSize.width) / 2)
            cgwidth = contextSize.width
            cgheight = contextSize.width
        }
        
        let rect: CGRect = CGRect.init(x: posX, y: posY, width: cgwidth, height: cgheight)
        
        // Create bitmap image from context using the rect
        let imageRef: CGImage = contextImage.cgImage!.cropping(to: rect)!
        
        // Create a new image based on the imageRef and rotate back to the original orientation
        let resultImage: UIImage = UIImage(cgImage: imageRef, scale: self.scale, orientation: self.imageOrientation)
        
        return resultImage
    }
} `
