### ISSUE TITLE
How to properly deal with interruptions

### ISSUE THREAD

**Issue by donaldpiret** [imaginary-cloud/CameraManager#55]
What is the proper way to stop recording and save the video when the recording gets interrupted (eg. by a phone call)? 
I've been trying to do this properly but can't seem to get the video to save, and I end up losing whatever recording I had made.

**Comment by torrao** [comment]
Hi @donaldpiret,

have you tried to do something like this in your ViewController?

```
import CoreTelephony

class ViewController: UIViewController {
    
    (...)
    private var callCenter = CTCallCenter()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        (...)
        
        callCenter.callEventHandler = { (call:CTCall!) in
            
            switch call.callState {
            case CTCallStateIncoming:
                self.cameraManager.stopVideoRecording({ (videoURL, error) -> Void in })
            default:
                break
            }
        }
```

**Comment by donaldpiret** [comment]
That worked brilliantly, thanks!

**Comment by donaldpiret** [comment]
It seems low battery warnings also interrupt the recording video without possibility of saving it. Any workaround for that?
