### ISSUE TITLE
Saving of video will silently fail occasionally

### ISSUE THREAD

**Issue by donaldpiret** [imaginary-cloud/CameraManager#57]
Hello,
We've had several reports from users using our app WeTime (which is using CameraManager), that in very rare occasions, the saving of their recording video would fail.
We've been trying to trace the exact location of the failure using remote logging tools and believe we have narrowed it down to the stopRecordingVideo method.

Our code looks like this:

```
Mobihelp.sharedInstance().leaveBreadcrumb("About to call cameraManager.stopRecordingVideo")
cameraManager.stopRecordingVideo(self.saveVideo)

...


private func saveVideo(tempVideoURL: NSURL?, error: NSError?) -> Void {
    Mobihelp.sharedInstance().leaveBreadcrumb("saveVideo called")
   ...
```

We see the first breadcrumb correctly being set, but in the cases where people lost their recorded video, saveVideo doesn't seem to ever have been actually called.

Looking at the stopRecordingVideo method, it seems that a lot could actually go wrong without us knowing about it (movieOutput could be nil, or it could not be recording).

What are your thoughts on getting some better handling of these edge cases (maybe using _show to display the error)?

**Comment by cathy810218** [comment]
This happens when I switch `cameraOutputMode` from `VideoWithMic` to `StillImage` and back to `VideoWithMic`. Not sure why that's happening though.

**Comment by torrao** [comment]
Closing this since there has not been any recent activity and newer versions have been released. 
Please open a new issue if the problem persists.
