### ISSUE TITLE
capturePictureWithCompletion call but not complete

### ISSUE THREAD

**Issue by anchanfx** [imaginary-cloud/CameraManager#58]
In example

```
cameraManager.capturePictureWithCompletion({ (image, error) -> Void in
    self.myImage = image             
})
```

in side { } never get called

**Comment by finekost** [comment]
Came along the same problem.
Make shure to set CameraOutputMode to "stillImage"

`_ = cameraManager.addPreviewLayerToView(cameraPreviewContainer, newCameraOutputMode: CameraOutputMode.stillImage)`

or
`cameraManager.cameraOutputMode = .stillImage`

debug with:
```
func capturePhoto() {
        print(cameraManager.cameraOutputMode)
    }
```

**Comment by torrao** [comment]
Closing this since there has not been any recent activity and newer versions have been released. 
Please open a new issue if the problem persists.
