### ISSUE TITLE
Insert previewLayer to subLayer of cameraView (Feature Request)

### ISSUE THREAD

**Issue by otymartin** [imaginary-cloud/CameraManager#59]
@nelanelanela @torrao 

Hey would really like to be able to add the preview layer to the `cameraView` sublayer that way its easier to add content on top of my `cameraView`. Specifically, I want to add a blur to my camera view along with buttons, labels and icons but the preview layer takes precedence.

I just switched from `CameraEngine` where what I'm trying to do worked perfectly.

``` swift
let layer = self.cameraEngine.previewLayer
        layer.frame = self.cameraView.bounds
        self.cameraView.layer.insertSublayer(layer, atIndex: 0)

//I could then add a blur effect on top of it like so
    //BLUR EFFECT
        let blurEffect = UIBlurEffect(style: .Dark)
        let blurEffectView = UIVisualEffectView(effect: blurEffect)
        blurEffectView.frame = self.cameraView.bounds
        blurEffectView.backgroundColor = UIColor.blackColor().colorWithAlphaComponent(0.7)
        blurEffectView.autoresizingMask = [.FlexibleWidth, .FlexibleHeight]
        self.cameraView.addSubview(blurEffectView)
```

**Comment by bryanbartow** [comment]
+1

**Comment by gbmksquare** [comment]
+1

**Comment by gbmksquare** [comment]
Workaround: just create a new `UIView` as a wrapper to camera view, and add the preview layer to the new `UIView`.

**Comment by torrao** [comment]
Closing this issue since this can be achieved using @gbmksquare solution.
