### ISSUE TITLE
When you stop and resume capture session, orientation detection doesn't work anymore

### ISSUE THREAD

**Issue by sarbogast** [imaginary-cloud/CameraManager#6]
I have modified the demo project in order to add the possibility to switch to another screen and then come back. This way, viewWillDisappear is called on ViewController, and then viewWillAppear is called again, resulting in stopCaptureSession being called and then resumeCaptureSession. In that case, when you try to switch from portrait to landcape, the preview is all skewed.

**Comment by nelanelanela** [comment]
Thanks for spotting this one. It's fixed.
