### ISSUE TITLE
xcode 8

### ISSUE THREAD

**Issue by dimohamdy** [imaginary-cloud/CameraManager#60]
can you make new branch for swift2.3 and swift3?

**Comment by gamafranco** [comment]
@dimohamdy thanks so much for the contribution. @torrao has his hands tied up this week and the next. We'll do the merge ASAP.

**Comment by dimohamdy** [comment]
@gamafranco  thanks for replay

**Comment by dimohamdy** [comment]
@torrao  speed recovery

**Comment by illyaBakurov** [comment]
Please, could you update to support swift3 and xCode8?

**Comment by dimohamdy** [comment]
@illyaBakurov  swift 3 branch check this
https://github.com/dimohamdy/CameraManager/tree/swift-3.0

**Comment by torrao** [comment]
Merged and released, sorry for the delay.

**Comment by dimohamdy** [comment]
@torrao  no problem
