### ISSUE TITLE
Feature request: Add option of what album to write image to

### ISSUE THREAD

**Issue by niklassaers** [imaginary-cloud/CameraManager#62]
Hey, thanks for writing such a nice manager.

When setting writeFilesToPhoneLibrary it will write the file to the library, but it'd be nice to have the option of setting what album to write it to.

Alternatively, a hook for the completionblock of writeImageDataToSavedPhotosAlbum would make it equally simple? Then again, writeImageDataToSavedPhotosAlbum is deprecated in iOS 9, so I'm a bit confused as to what direction would be preferable. :-)

**Comment by torrao** [comment]
Feature added in v4.2.0
