### ISSUE TITLE
CameraManager detects flash on front camera, but it shouldn't

### ISSUE THREAD

**Issue by quiKsilverItaly** [imaginary-cloud/CameraManager#63]
I found a weird behavior, when I use the front camera of my iPhone 5s. The front camera doesn't support flash. But if I call 
`cameraManager.hasFlash` 
it returns "true" anyway. Why is that? 

If I try to make a video now, the app starts recording accordingly with the front camera.. but at the start of the recording the flash of the back camera turns on for a second for no reason at all. 

Same behavior with the example app.

Anyway thank you a lot for this great library!

**Comment by Sousa5** [comment]
Hi @quiKsilverItaly 

The captureDevice.hasFlash property returns true if the device have flash available and not if the selected camera have flash.
The issue with recording video when flash is on will be fixed in the next minor version.

Thanks
