### ISSUE TITLE
video orientation not set after camera switch

### ISSUE THREAD

**Issue by sketchycode** [imaginary-cloud/CameraManager#64]
After I switch the camera (front to back or back to front) while `.shouldRespondToOrientationChanges` is set to `true`, and begin recording in a landscape orientation (either right or left), the output video will be rotated incorrectly.

My current "fix" is to just call `_orientationChanged()` inside the `cameraDevice` didSet block. This probably isn't a universal fix, though, since not everyone will want the camera to respond to orientation changes. I can investigate a more complete fix and submit a PR if you'd like. Let me know.

**Comment by torrao** [comment]
Fixed in v.4.2.0
