### ISSUE TITLE
Carthage installation no longer working with Xcode 8

### ISSUE THREAD

**Issue by geoherna** [imaginary-cloud/CameraManager#65]
Recently updated to Xcode 8 since the general release was today and I get errors overtime I try and build with carthage. I get the following errors:

-scheme CameraManager -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* CLEAN FAILED **

Any suggestions? 

Thanks in advance!

**Comment by torrao** [comment]
@geoherna I believe that you are obligated to have a Code Signing Identity to build with Xcode 8. Can you please check if that's what causing the errors?
