### ISSUE TITLE
Cause Leak

### ISSUE THREAD

**Issue by kai1004pro** [imaginary-cloud/CameraManager#74]
when I declare let cameraManager = CameraManager(), it immediately cause 2 leaks. Does anyone have any idea ?

**Comment by allanscofield** [comment]
Same problem here

**Comment by torrao** [comment]
@kai1004pro @allanscofield,

I've profiled the last version of CameraManager with Instruments and didn't have any memory leaks. 
If the problem still persists for you please feel free to open a new PR.
