### ISSUE TITLE
File saving

### ISSUE THREAD

**Issue by ossmalpha** [imaginary-cloud/CameraManager#75]
Files are no more automatically being saved to photo library. Please check.

**Comment by Sousa5** [comment]
Hi @ossmalpha

We cannot reproduce this issue in the example app, you allowed camera manager access to photo library?

Thanks

**Comment by torrao** [comment]
@ossmalpha 

do you still have this issue using v3.1.4?

**Comment by ossmalpha** [comment]
I am not using this library anymore.
