### ISSUE TITLE
CameraManager Wont Build -- Xcode 8 -- Swift 2.3

### ISSUE THREAD

**Issue by caat91** [imaginary-cloud/CameraManager#76]
Hello!

I have been using CameraManager for the last couple of months and everything have been great. Today I reinstalled my pods and I got the following error when building: 

<img width="303" alt="screen shot 2016-10-27 at 5 50 56 pm" src="https://cloud.githubusercontent.com/assets/2414186/19786837/f0033526-9c6d-11e6-9f98-b86dacceaf79.png">

If I unluck the code and fix that one I get another group of errors:

<img width="303" alt="screen shot 2016-10-27 at 5 51 58 pm" src="https://cloud.githubusercontent.com/assets/2414186/19786867/136c338c-9c6e-11e6-8f9c-9f3f4381ff6d.png">

And it goes on after that.

I am working with Xcode 8 and Swift 2.3

Thank you for the help and for the great work you do.

**Comment by nakamuri** [comment]
I am having this same issue. Recently updated XCode but I don't know why that would cause a problem.

**Comment by nakamuri** [comment]
This is where the error is happening for me:

<img width="847" alt="screen shot 2016-10-28 at 4 31 12 pm" src="https://cloud.githubusercontent.com/assets/1576895/19823018/062e7996-9d2c-11e6-8483-025fe823cac3.png">
