### ISSUE TITLE
how can I limit video recording time to 10 seconds?

### ISSUE THREAD

**Issue by nalogowiec** [imaginary-cloud/CameraManager#79]
Like in the topic - is there a possibility of limiting the recording time of each video to 10 seconds?

**Comment by 4ndrey** [comment]
I had the the same task and solved it by using external timer

**Comment by nalogowiec** [comment]
@4ndrey can you provide some simple code for that?

**Comment by 4ndrey** [comment]
`
            cameraManager.startRecordingVideo()
            videoTimer = Timer.scheduledTimer(timeInterval: 0.1, target: self, selector: #selector(onTimer), userInfo: nil, repeats: true)
            ...


    func onTimer() {
        progressView.value += 0.1
        progressView.setProgress(value: progressView.value, animationDuration: 0.05, completion: {
            if self.progressView.value >= 10 {
                if let timer = self.videoTimer { timer.invalidate() }
                self.stopVideoRecording()
            }
        })
    }

    func stopVideoRecording() {
        if let timer = videoTimer { timer.invalidate() }
        cameraManager.stopVideoRecording { [unowned self] videoURL, error in
                    ....
        }
    }
`

**Comment by nalogowiec** [comment]
thanks @4ndrey , could you just tell me how did you initialize the videoTimer? what kind of variable is it?

**Comment by 4ndrey** [comment]
`var videoTimer: Timer?` 
Do you ever write in swift before?
