### ISSUE TITLE
videoWithMic mode is not working

### ISSUE THREAD

**Issue by 4ndrey** [imaginary-cloud/CameraManager#81]
Trying to get .videoWithMic mode working but got several issues:
1. It doesn't ask permission to record audio via AVAudioSession.sharedInstance().requestRecordPermission and therefore crashes
2. After manually allowing audio recoding permission it shows black screen instead of video capture

**Comment by Sousa5** [comment]
Hi @4ndrey 

Are sou using the example app?

Thanks

**Comment by 4ndrey** [comment]
no, my own app

**Comment by torrao** [comment]
@4ndrey,

do you still have this issue in a newer version?

**Comment by 4ndrey** [comment]
No,thanks!

14 июня 2017 г. 9:50 PM пользователь "Ricardo Torrão" <
notifications@github.com> написал:
