### ISSUE TITLE
flashMode on front camera

### ISSUE THREAD

**Issue by Arnoymous** [imaginary-cloud/CameraManager#82]
When cameraDevice is .front hasFlash return true but there is no flash during the capture.
Maybe remove the captureDevice.position == AVCaptureDevicePosition.back in _updateTorch() ?

**Comment by Sousa5** [comment]
Hi @Arnoymous 

The hasFlash property is based on the device and not on the selected camera and currently, apple devices just have flash on the back camera that's why we are checking the device position. 

Thanks

**Comment by Arnoymous** [comment]
@Sousa5 nop iPhone 6S has front flash

**Comment by torrao** [comment]
@Arnoymous 

fixed in v3.1.4 👍
