### ISSUE TITLE
Zoom of front camera not working.

### ISSUE THREAD

**Issue by jf367** [imaginary-cloud/CameraManager#84]
This code in _zoom() is wrong:

    fileprivate func _zoom(_ scale: CGFloat) {
        do {
            let captureDevice = AVCaptureDevice.devices().first as? AVCaptureDevice
            try captureDevice?.lockForConfiguration()
            ...

In my case, the first device is the back camera and the second one is the front one. The current code causes the back camera to be zoomed when I switch to the front one. In addition, when the back camera is not properly initialized and it has a smaller max zoom scale than the front camera, zooming too much on the front camera will cause "array index out of range" error and crash.
The code should be:

     fileprivate func _zoom(_ scale: CGFloat) {
        do {
            let captureDevice = (cameraDevice == .Front ? frontCameraDevice : backCameraDevice)
            try captureDevice?.lockForConfiguration()
            ...

**Comment by torrao** [comment]
@jf367 

fixed on v3.1.4 👍
