### ISSUE TITLE
Allow video and still image at same time

### ISSUE THREAD

**Issue by brightsider** [imaginary-cloud/CameraManager#86]
I want to release camera like in Snapchat and can't because you're not allow this in your library.

**Comment by gamafranco** [comment]
Thank @brightsider. Can you be more specific on what is blocking you to achieve your goal?

**Comment by brightsider** [comment]
If enabled videoWithMic and trying to make still image, then app crashes

**Comment by Kandhal** [comment]
Can anyone find a solution for this issue ?? still its happening...

**Comment by torrao** [comment]
@brightsider and @Kandhal,

allowing video and still image at the same time is currently out of scope.
