### ISSUE TITLE
stopVideoRecording not working

### ISSUE THREAD

**Issue by appcelerate** [imaginary-cloud/CameraManager#87]
Hi Guys, 

i am trying to build a camera app and i want to start stop the record with the same IBAction.

```swift
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        cameraManager.addPreviewLayerToView(previewLayerOutlet)
        cameraManager.cameraDevice = .back
        cameraManager.cameraOutputMode = .videoWithMic
        cameraManager.cameraOutputQuality = .medium
        cameraManager.writeFilesToPhoneLibrary = true
        cameraManager.showAccessPermissionPopupAutomatically = true
    }
```
```swift
@IBAction func startVideoRecording(_ sender: UIButton) {
        if sender.isSelected {
            cameraManager.stopVideoRecording({ (videoURL, error) -> Void in
                print(videoURL!.absoluteString)
            })
        }else{
            cameraManager.startRecordingVideo()
        }
        sender.isSelected = !sender.isSelected
    }
```
But 
```swift
print(videoURL!.absoluteString) 
```
never called. Any hint what I did wrong :/

Thanks

**Comment by appcelerate** [comment]
Ok now it called sometimes but not ever time. Its called randomly.

```Swift
cameraManager.stopVideoRecording({ (videoURL, error) -> Void in
                    if (videoURL != nil){
                        self.timer.invalidate()
                        self.createHighlightClips()
                        if let errorOccured = error {
                            self.cameraManager.showErrorBlock("Error occurred", errorOccured.localizedDescription)
                        }
                    }else{
                        self.timer.invalidate()
                    }
                })```

@gamafranco could u help me in this?

**Comment by nishantshrestha** [comment]
were you able to resolve this @appcelerate?

**Comment by Luccifer** [comment]
Same question...

**Comment by Luccifer** [comment]
<img width="773" alt="screen shot 2017-07-08 at 13 46 53" src="https://user-images.githubusercontent.com/1053009/27984645-f5af54da-63e3-11e7-9f53-fb93c779d89f.png">

So isRecording = false, thats the problem, but why, if we just started the session? Bug somewhere..

**Comment by Luccifer** [comment]
Okey, I researched a bit and found that: 
<img width="776" alt="screen shot 2017-07-08 at 13 55 21" src="https://user-images.githubusercontent.com/1053009/27984704-2511ab46-63e5-11e7-9e15-2ba7fb31c9e1.png">
<img width="477" alt="screen shot 2017-07-08 at 13 55 09" src="https://user-images.githubusercontent.com/1053009/27984705-25368fba-63e5-11e7-9457-2d700106173a.png">

But how actually it can be .stillImage, if I have hardcoded it to .videoWithMic?

**Comment by Luccifer** [comment]
After that: cameraIsReady = false caused the problem, that property cameraOutputMode can't be changed...

**Comment by Luccifer** [comment]
The framework has a lot of circles... The property cameraIsSetup changed and reinited a lot... A lot of dependences, not SOLID.. Better to refactor it, I think, the proper for outputMode still not changed from .stillImage to .videoWithMic...

**Comment by Luccifer** [comment]
So, the problem was  in 

`
open func addLayerPreviewToView(_ view: UIView, newCameraOutputMode: CameraOutputMode, completion: ((Void) -> Void)?) -> CameraState {
        if _canLoadCamera() {
            if let _ = embeddingView {
                if let validPreviewLayer = previewLayer {
                    validPreviewLayer.removeFromSuperlayer()
                }
            }
            if cameraIsSetup {
                _addPreviewLayerToView(view)
                cameraOutputMode = newCameraOutputMode
                if let validCompletion = completion {
                    validCompletion()
                }
            } else {
                _setupCamera({ Void -> Void in
                    self._addPreviewLayerToView(view)
                    self.cameraOutputMode = newCameraOutputMode
                    if let validCompletion = completion {
                        validCompletion()
                    }
                })
            }
        }
        return _checkIfCameraIsAvailable()
    }
`
If you not specify the newCameraOutputMode: CameraOutputMode in arguments to function it will definitely set to .stillImage... maybe if should be optional? Yes, it should, cause not everybody uses all three/two arguments to this function, or you should expand your readme and setupGuide on main page of this framework... Thanks for spending our time. Cheers!
