### ISSUE TITLE
Temporary Image Storing Questio

### ISSUE THREAD

**Issue by AdventuresOfMar** [imaginary-cloud/CameraManager#89]
Greetings, I'm still piecing through the documentation so apologies if covered already but, is it possible to temporarily store and pass image from camera view controller to preview view controller without saving to phone?

Attempting to make a filter type controller so want to temporarily house the image in app if possible before saving to photo library so that user can make their changes to the image and then decide later on if they'd like to save image to phone

**Comment by c-sharma** [comment]
Set the following property for a CameraManager object -
`cameraManager.writeFilesToPhoneLibrary = false`

You can later save the image received in capturePictureWithCompletion callback logic save to Photos as convenient.
