### ISSUE TITLE
Shuttering option 

### ISSUE THREAD

**Issue by jackpaster** [imaginary-cloud/CameraManager#90]
@gamafranco @davidortinau @pedrorolo @davidy @lexrus I love your project very much, but I'm having a problem. Instead of taking one photo and presenting the next viewcontroller the image. I want the user to hold down on the camera button and burst of images will be taken until they let go of the camera button. Once they let go, the array of images taken will be passed onto the next view controller. Can you please implement this

**Comment by patthehuman** [comment]
You should write your own code for this.
