### ISSUE TITLE
SubViews of camera view disappear 

### ISSUE THREAD

**Issue by geoherna** [imaginary-cloud/CameraManager#93]
I have added an IBOutlet named `cameraView` which as you would expect is the view that the camera gets added to. I have a button within that view that I want to use to take the photo, but when the camera gets added to the view, the button shows up for a second and then disappears. Any suggestions on how to fix this or is this an issue with the framework. Honestly not sure. Currently trying: 

```
override func viewDidAppear(_ animated: Bool) {
        self.addCameraToView()
        cameraView.bringSubview(toFront: takePhoto) //Not Working
    }

    
    private func addCameraToView(){
        cameraManager.addPreviewLayerToView(cameraView)
        
        cameraManager.showErrorBlock = { [weak self] (erTitle: String, erMessage: String) -> Void in
            
            //Handle Issues
        }
    }
```

I thought the bringSubview() function might be a solution but it isn't working. Any help would be greatly appreciated.

**Comment by Bengejd** [comment]
@geoherna Did you end up finding a solution to this? I am running into a similar issue right now.

**Comment by ZUCheema** [comment]
Don't add subviews to previewView, use previewView just for camera, add another view above previewView in superview and add those subviews to that view. This will will always stay above previewView based on position of view hierarchy.
