### ISSUE TITLE
Issues with deprecated functions in iOS10 using this pod

### ISSUE THREAD

**Issue by supergera13** [imaginary-cloud/CameraManager#95]
Hi guys, i'm new to github. Thanks for the work done on this pod. I'm integrating it because i'm building my instagram-like app, but i found 16 deprecated methods in the cameramanager.swift file, all about AVDevicesDiscoverySession and StillImageOutput. I changed them with what xcode tells me, but more errors pops up than before. I don't know what to do. Anyone can help me?

**Comment by torrao** [comment]
@supergera13 

which version of Swift are you using?

**Comment by torrao** [comment]
@supergera13 due to inactivity in this issue, I'm closing it. If you need further assistance, please feel free to reopen it.
