### ISSUE TITLE
How can i get saved video path from phone gallery ?

### ISSUE THREAD

**Issue by rajeshsonu** [imaginary-cloud/CameraManager#99]
After capturing video im saving to gallery using 
cameraManager.writeFilesToPhoneLibrary = true
But what i want is the saved video file path.

**Comment by torrao** [comment]
@rajeshsonu,

in order for you to do that, you just need to:

```
cameraManager.stopVideoRecording({ (videoURL, error) -> Void in
 // videoURL is the saved video file path
})
```
